on:
  release:
    types: [created]

jobs:
  release_projects:
    name: "${{matrix.project}}-release-${{matrix.target}}"
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
        project: [sim-ann, art-1, ant, neuro, genetic, kosko, hopfield]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md"
          SRC_DIR: ${{ matrix.project }}
          TOOLCHAIN_VERSION: "nightly"
          ARCHIVE_NAME: "${{matrix.project}}-release-${{matrix.target}}"
